version: '2'

services:
        nginx:
                image: nginx:latest
                ports:
                        - 3002:80
                volumes:
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                        - ./static/:/var/www/html/static/
        web:
                build: ./Web
                expose:
                        - 3000
                volumes:
                        - ./static:/usr/src/app/static
                env_file:
                        - ./.env
        bot:
                build: ./Bot
                expose:
                        - 3001
                env_file:
                        - ./.env.bot
                        - ./.env
                volumes:
                        - ./static:/usr/src/app/static
