on: 
  push:
    branch:
      - master

name: 'build'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0.0.5
    - name: Docker build
      run: |
        echo "123456789:abcdefghijklmoonpqrstuvwxyz" > .env
        docker-compose up -d --build
